language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION 'set concurrentRestrictions in Global += Tags.limit(Tags.Compile, 2)' compile test:compile test
scala:
  - 2.10.3
jdk:
  - oraclejdk7
  - openjdk7
notifications:
  email:
    - johannes@spray.io
    - mathias@spray.io